services:

  db:
    image: mariadb:11.3.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  rabbitmq:
      image: rabbitmq:3.13.0-management
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
      ports:
        - "5672:5672"
        - "15672:15672"