services:

#  book-service:
#    container_name: book-service
#    build: .
#    command: "poetry run python ./manage.py runserver 0.0.0.0:8000"
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db

  db:
    container_name: db
    image: postgres:17-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookdb
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
