# Generated by Django 5.1.2 on 2024-10-27 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=500)),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('book_id', models.PositiveIntegerField()),
                ('book_title', models.TextField(default='')),
                ('book_authors', models.JSONField(default=list)),
                ('book_subjects', models.JSONField(default=list)),
            ],
        ),
    ]
